# Generated by Django 4.1.2 on 2022-10-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('about', models.TextField(max_length=500)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('is_liked', models.BooleanField(default=False)),
            ],
        ),
    ]
